export enum InformationRequirementStatusType {
  //#region ODataApi Members
  UNVALIDATED = 'UNVALIDATED',
  VALIDATED = 'VALIDATED',
  CONSOLIDATED = 'CONSOLIDATED',
  REDUNDANT = 'REDUNDANT',
  APPROVED = 'APPROVED',
  IN_ACTION = 'IN_ACTION',
  STOPPED = 'STOPPED',
  PARTIALLYCOMPLETED = 'PARTIALLYCOMPLETED',
  COMPLETED = 'COMPLETED',
  UNFULFILLED = 'UNFULFILLED',
  //#endregion
}
